// my-web/src/lib/components/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		children: Snippet;
		class?: string;
	}

	let { children, class: className = '' }: Props = $props();
</script>

<div class="bg-surface border border-border rounded-3xl p-10 backdrop-blur-md {className}">
	{@render children()}
</div>

// src/components/Card.tsx
import type { ReactNode } from 'react';

interface Props {
	children: ReactNode;
	className?: string;
	padding?: boolean;
}

export default function Card({ children, className = '', padding = true }: Props) {
	return (
		<div
			className={`bg-surface border border-border rounded-3xl ${padding ? 'p-10' : ''} backdrop-blur-md ${className}`}
		>
			{children}
		</div>
	);
}
