// my-web/src/lib/components/Project.svelte
<script lang="ts">
	import { marked } from 'marked';
	import Card from './Card.svelte';

	interface ProjectProps {
		title: string;
		heading?: string;
		image?: string;
		size: 'small' | 'large';
		altText?: string;
	}

	let { title, heading, image, size, altText }: ProjectProps = $props();

	// find all summaries via glob
	const summaries: Record<string, { default: string }> = import.meta.glob(
		'/src/lib/projects/*/*.md',
		{
			query: '?raw',
			eager: true
		}
	);

	// make a renderer so that links in markdown get parsed into <a> that open in new tab
	const renderer = new marked.Renderer();
	renderer.link = ({ href, title, text }) => {
		return `<a href="${href}" target="_blank" rel="noopener noreferrer"${title ? ` title="${title}"` : ''}>${text}</a>`;
	};
	marked.setOptions({ renderer });

	const rawSummary = $derived(
		summaries[`/src/lib/projects/${title.toLowerCase()}/${title.toLowerCase()}_summary.md`]
			?.default ?? 'Could not get ' + title + "\'s summary"
	);
	const summaryHtml = $derived(marked.parse(rawSummary));

	const styling = $derived(size === 'large' ? 'flex flex-col' : 'flex flex-row');
</script>

<Card class={styling + ' gap-4'}>
	{#if image}
		<div class="flex items-center justify-center {size === 'large' ? 'order-2' : 'order-first'}">
			<img
				src={image}
				alt={title + ' image failed to load'}
				loading="lazy"
				class="rounded-xl border border-border"
			/>
		</div>
	{/if}
	<div class={size === 'large' ? 'order-1' : ''}>
		<header>{heading ?? title}</header>
		<div class="space-y-4 pt-4">
			{#if altText}
				{altText}
			{:else}
				{@html summaryHtml}
			{/if}
		</div>
	</div>
</Card>

// src/components/Project.tsx
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { marked } from 'marked';
import Card from './Card';

interface ProjectProps {
	title: string;
	heading?: string;
	image?: string;
	size: 'small' | 'large';
	altText?: string;
}

const renderer = new marked.Renderer();
renderer.link = ({ href, title, text }) => {
	return `<a href="${href}" target="_blank" rel="noopener noreferrer"${title ? ` title="${title}"` : ''}>${text}</a>`;
};
marked.setOptions({ renderer });

function loadSummary(title: string): string {
	const folder = title.toLowerCase();
	const path = join(process.cwd(), 'src/lib/projects', folder, `${folder}_summary.md`);
	try {
		return readFileSync(path, 'utf-8');
	} catch {
		return `Could not get ${title}'s summary`;
	}
}

export default function Project({ title, heading, image, size, altText }: ProjectProps) {
	const summaryHtml = altText ? '' : (marked.parse(loadSummary(title)) as string);
	const styling = size === 'large' ? 'flex flex-col' : 'flex flex-row';

	return (
		<Card className={styling + ' gap-4'}>
			{image && (
				<div
					className={`flex items-center justify-center ${size === 'large' ? 'order-2' : 'order-first'}`}
				>
					{/* eslint-disable-next-line @next/next/no-img-element */}
					<img
						src={image}
						alt={title + ' image failed to load'}
						loading="lazy"
						className="rounded-xl border border-border"
					/>
				</div>
			)}
			<div className={size === 'large' ? 'order-1' : ''}>
				<header>{heading ?? title}</header>
				<div className="space-y-4 pt-4">
					{altText ? altText : <div dangerouslySetInnerHTML={{ __html: summaryHtml }} />}
				</div>
			</div>
		</Card>
	);
}
